#! /bin/bash

    echo -e "\n"
	echo "Hello Usare:"
	echo "------"
	echo ""
	echo "I think your brain hasn't exploded yet, it should definitely explode from this task. Please don't look at tasks like a child"
	echo ""
	echo "--------"
    echo "Your assignment!"
	echo -e ""
	echo -e ""
	echo -e "when you find a password from a file, hide from the previous file, and "
    echo -e "when you link the ones that have the names of the files, if you use "
    echo -e ".challange1, it will give you a flag"
	echo ""
	echo "Next step:"
	echo "You will go to files adn find fiels"
	echo ""
	echo -e ""
	echo -e ""
	echo ""